package Main;

import Main.MainFrame;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author zahid
 */
public class SplashScreen1 extends javax.swing.JFrame {

    /**
     * Creates new form SplashScreen
     */
    public SplashScreen1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();
        loadingBar = new javax.swing.JProgressBar();
        loadingLabel = new javax.swing.JLabel();
        loadingValue = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/baltaci.com.png"))); // NOI18N
        logoLabel.setText("jLabel1");
        jPanel1.add(logoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 420, 310));

        loadingBar.setBackground(new java.awt.Color(0, 0, 0));
        loadingBar.setForeground(new java.awt.Color(51, 51, 51));
        loadingBar.setBorder(null);
        jPanel1.add(loadingBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 900, 30));

        loadingLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        loadingLabel.setForeground(new java.awt.Color(0, 0, 0));
        loadingLabel.setText("Loading...");
        jPanel1.add(loadingLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 380, 40));

        loadingValue.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        loadingValue.setForeground(new java.awt.Color(0, 0, 0));
        loadingValue.setText("%0");
        jPanel1.add(loadingValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 420, 70, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SplashScreen1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SplashScreen1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SplashScreen1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SplashScreen1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        SplashScreen1 splashScreen = new SplashScreen1();
        splashScreen.setVisible(true);

        try {

            for (int i = 0; i <= 100; i++) {
                Thread.sleep(75);
                splashScreen.loadingValue.setText("%" + i);

                if (i == 10) {
                    splashScreen.loadingLabel.setText("Turning on Modules...");
                }
                if (i == 20) {
                    splashScreen.loadingLabel.setText("Loading Modules...");
                }
                if (i == 50) {
                    splashScreen.loadingLabel.setText("Connecting to Database...");
                }
                if (i == 70) {
                    splashScreen.loadingLabel.setText("Connection Successful...");
                }
                if (i == 80) {
                    splashScreen.loadingLabel.setText("Loading Application...");
                }
                splashScreen.loadingBar.setValue(i);

            }

            MainFrame mainFrame = new MainFrame();
            mainFrame.show();
            splashScreen.dispose();

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, e);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar loadingBar;
    private javax.swing.JLabel loadingLabel;
    private javax.swing.JLabel loadingValue;
    private javax.swing.JLabel logoLabel;
    // End of variables declaration//GEN-END:variables
}
