package CarSalesSystem;

import Main.MainFrame;

/**
 *
 * @author zahid
 */
public class MainPage extends javax.swing.JPanel {

    public MainFrame mainFrame ;
   

    /**
     * Creates new form MainPage
     */
    public MainPage() {
        initComponents();
    }
    
    public MainPage(MainFrame mainFrame){
        this.mainFrame = new MainFrame();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        baltaciLabel = new javax.swing.JLabel();
        logintTypeLabel = new javax.swing.JLabel();
        questionLabel = new javax.swing.JLabel();
        adminButton = new javax.swing.JButton();
        dealerButton = new javax.swing.JButton();
        customerButton = new javax.swing.JButton();
        vehicleButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));
        setPreferredSize(new java.awt.Dimension(1000, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMinimumSize(new java.awt.Dimension(1000, 600));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        titleLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(0, 0, 51));
        titleLabel.setText("VEHICLE MANAGAMENT SYSTEM");
        add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 820, 70));

        baltaciLabel.setFont(new java.awt.Font("Snap ITC", 0, 14)); // NOI18N
        baltaciLabel.setForeground(new java.awt.Color(255, 255, 0));
        baltaciLabel.setText("Made by baltaci.com");
        add(baltaciLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 200, -1));

        logintTypeLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        logintTypeLabel.setForeground(new java.awt.Color(255, 255, 255));
        logintTypeLabel.setText("Please select a login or registration type");
        add(logintTypeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 360, 40));

        questionLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        questionLabel.setForeground(new java.awt.Color(255, 255, 255));
        questionLabel.setText("Do you just want to look at cars?");
        add(questionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 160, 310, -1));

        adminButton.setBackground(new java.awt.Color(0, 0, 51));
        adminButton.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        adminButton.setForeground(new java.awt.Color(255, 255, 255));
        adminButton.setText("ADMIN");
        adminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminButtonActionPerformed(evt);
            }
        });
        add(adminButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 160, 50));

        dealerButton.setBackground(new java.awt.Color(0, 0, 51));
        dealerButton.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        dealerButton.setForeground(new java.awt.Color(255, 255, 255));
        dealerButton.setText("DEALER");
        dealerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dealerButtonActionPerformed(evt);
            }
        });
        add(dealerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 160, 50));

        customerButton.setBackground(new java.awt.Color(0, 0, 51));
        customerButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        customerButton.setForeground(new java.awt.Color(255, 255, 255));
        customerButton.setText("CUSTOMER");
        add(customerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, -1, 50));

        vehicleButton.setBackground(new java.awt.Color(0, 0, 51));
        vehicleButton.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        vehicleButton.setForeground(new java.awt.Color(255, 255, 255));
        vehicleButton.setText("VEHICLES");
        add(vehicleButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 270, -1, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void adminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminButtonActionPerformed

//        AdminLoginPanel adminLoginPanel = new AdminLoginPanel();
//        adminLoginPanel.mainFrame = mainFrame;
//        mainFrame.setPage(adminLoginPanel);
//        
        

    }//GEN-LAST:event_adminButtonActionPerformed

    private void dealerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dealerButtonActionPerformed
//        DealerLoginPanel dealerLoginPanel = new DealerLoginPanel();
//        dealerLoginPanel.mainFrame =mainFrame;
//        mainFrame.setPage(dealerLoginPanel);
    }//GEN-LAST:event_dealerButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminButton;
    private javax.swing.JLabel baltaciLabel;
    private javax.swing.JButton customerButton;
    private javax.swing.JButton dealerButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logintTypeLabel;
    private javax.swing.JLabel questionLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton vehicleButton;
    // End of variables declaration//GEN-END:variables
}
